version: 1.0
os: linux
files:
  - source: /home/ubuntu/learn_actions
    destination: /home/ubuntu/learn_actions/deploy
    overwrite: true
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ubuntu
