name: Node.js CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  deploy:
    name: deploy to ec2
    runs-on: ubuntu-latest
    
    steps:
    - run: echo ${{ secrets.REMOTE_TEST }}
    - uses: actions/checkout@v2
    - uses: easingthemes/ssh-deploy@v4.1.8
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
          
          
